spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://aws.cidtckobgf3m.ap-northeast-2.rds.amazonaws.com/awsDB
    username: root
    password: cksdl30104
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: ture

